settings:
  username: "Knerio"
  commit_msg: "âš¡ Update README with the recent activity"
  max_lines: 5
  readme_file: "./README.md"
  disabled_events: ["psuh"]
  url_text: "{REPO}{ID}"
  date: # Date Settings are ignored
    timezone: "GMT+00:00"
    text: "Last Updated: {DATE}"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
  commit_username: "readme-bot"
  commit_email: "41898282+github-actions[bot]@users.noreply.github.com"
messages:
  push: "Pushed on {ID} in {REPO} {DATE}"
  comments: "ğŸ’¬ Commented on {ID} in {REPO} {DATE}"
  issue_opened: "â—ï¸ Opened issue {ID} in {REPO} {DATE}"
  issue_closed: "âœ”ï¸ Closed issue {ID} in {REPO} {DATE}"
  pr_opened: "ğŸ’ª Opened PR {ID} in {REPO} {DATE}"
  pr_closed: "âŒ Closed PR {ID} in {REPO} {DATE}"
  pr_merged: "ğŸ‰ Merged PR {ID} in {REPO} {DATE}"
  create_repo: "ğŸ“” Created new repository {REPO} {DATE}"
  fork_repo: "ğŸ”± Forked {FORK} from {REPO} {DATE}"
  wiki_create: "ğŸ“– Created new wiki page {WIKI} in {REPO} {DATE}"
  added_member: "ğŸ¤ Became collaborator on {REPO} {DATE}"
  changes_approved: "ğŸ‘ Approved {ID} in {REPO} {DATE}"
  changes_requested: "ğŸ”´ Requested changes in {ID} in {REPO} {DATE}"
  new_release: "âœŒï¸ Released {ID} in {REPO} {DATE}"
  new_star: "â­ Starred {REPO} {DATE}"
