name: Hourly README Updater

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  activity:
    name: "Updates the repo's README with lastest activities"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: Readme-Workflows/recent-activity@2.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
